from pydantic import BaseModel, Field
from datetime import datetime, timezone
from typing import Optional

class Post(BaseModel):
    platform: str = Field(..., description="Platform name e.g., LinkedIn, Facebook")
    content: str = Field(..., description="Content of the post")
    image_data: Optional[bytes] = Field(None, description="Binary image data generated by Gemini")
    timestamp: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="Post creation timestamp (UTC)"
    )
